### ISSUE TITLE
Pub/Sub publisher hangs forever if invoked with non-existed service account

### ISSUE THREAD

**Issue by kir-titievsky** [googleapis/python-pubsub#19]
2. OS type and version: Mac OS 10.13.6
3. Python version and virtual environment information: `python --version`
4. google-cloud-<service> version:  Python 2.7.15 in virtualenv

#### Steps to reproduce

1. Create a service account with pubsub publisher permissions (easiest in Cloud Console).
2. Create and download a key for for the account: gcloud auth activate-service-account service-account@...gserviceaccount.com --key-file key.json
3. Attempt running the code below as python pub.py $PROJECT some_topic_name

End up in a hanging state -- you can't even cancel the python process, only kill -9. 

Expected behavior: the code fails immediately with a permission denied error.  Note that gcloud version of the command does exactly that. 

#### Code example
pub.py
```
import sys
  
from google.cloud import pubsub_v1


def get_callback(api_future, data):
    """Wraps message data in the context of the callback."""
    def callback(api_future):
       if api_future.exception():
            print("There was a problem with message {}".format(data))
       else:
            print("Published message {} now has message_id {}".format(
                data, api_future.result()))
    return callback

def pub(project_id, topic_name):
    """Publishes multiple messages to a Pub/Sub topic."""
    client = pubsub_v1.PublisherClient()
    topic_path = client.topic_path(project_id, topic_name)    # Data must be a bytestring

    data = "Hello, World!"
    data = data.encode('utf-8')

    # When you publish a message, the client returns a future.
    api_future = client.publish(topic_path, data=data)
    api_future.add_done_callback(get_callback(api_future, data))


if __name__ == '__main__':
    _, p, t = sys.argv
    pub(p, t)
~                                                                                                  
~                 
```

**Comment by plamut** [comment]
Bump. Do we have any status update on this? Thanks.

**Comment by plamut** [comment]
New year, new bump. :)

Has the backend folks been notified, any status update? Thanks.

**Comment by anguillanneuf** [comment]
@plamut I think this issue is resolved, invalid credentials fail the program immediately with 403 PermissionDenied error: `google.api_core.exceptions.PermissionDenied: 403 User not authorized to perform this action.` Also, we have dropped Python 2 support now.

**Comment by plamut** [comment]
@anguillanneuf I confirm that the client now fails immediately:
```
RefreshError (Invalid grant: account not found)
```
It does try to repeat the request, but that's OK, since it can be be interrupted with <kbd>Ctrl</kbd>+<kbd>C</kbd> (tested on Ubuntu 18.04).

We can keep this closed, yes.

**Comment by anguillanneuf** [comment]
Thanks for confirming Peter!

**Comment by deelefrati** [comment]
I'm still having this problem with python version `3.10.12` and `google-cloud-pubsub 2.18.0`.
